DemoWebApplication/Models/SalesInvoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoWebApplication.Models
{
    public class SalesInvoice
    {
        //Sales Master Data
        public int SalesMasterId { get; set; }
        public int Accountnumber { get; set; }
        public string Accountname { get; set; }
        public int Billno { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Invoicedate { get; set; }
        public string PaymentmodeCash { get; set; }
        public string CAddress { get; set; }
        public Nullable<long> Phoneno { get; set; }
        public string Manualno { get; set; }
        public System.DateTime Duedate { get; set; }
        public bool ApplyGst { get; set; }
        public string CustState { get; set; }
        public bool DontApplyGst { get; set; }
        public Nullable<decimal> NetBillAmount { get; set; }
        public Nullable<decimal> GstAmount { get; set; }
        public Nullable<decimal> Totalbillamount { get; set; }
        public Nullable<decimal> BillDiscount { get; set; }
        public Nullable<decimal> Paidamount { get; set; }
        public Nullable<decimal> Balanceamount { get; set; }

        // Sales Details Data
        public int SalesDetailId { get; set; }
        //public Nullable<int> Accountnumber { get; set; }
        //public Nullable<int> Billno { get; set; }
        public Nullable<int> Itemdetailid { get; set; }
        public string Batchno { get; set; }
        public string Godown { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> salesprice { get; set; }
        public Nullable<int> disc { get; set; }
        public Nullable<int> discamt { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> SGST { get; set; }
        public Nullable<int> CGST { get; set; }
        public Nullable<int> IGST { get; set; }
        public string HSNCode { get; set; }
        public Nullable<int> SGSTAmt { get; set; }
        public Nullable<int> SGSTTaxableAmt { get; set; }
        public Nullable<int> CGSTAmt { get; set; }
        public Nullable<int> CGSTTaxableAmt { get; set; }
        public Nullable<int> SrNo { get; set; }
        public Nullable<int> MRP { get; set; }
        public Nullable<int> PurchasePrice { get; set; }
        public Nullable<int> GST { get; set; }
        public Nullable<int> IGSTAmt { get; set; }
        public Nullable<int> IGSTTaxableAmt { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<decimal> totalamount { get; set; }

        //new Added 
        public string ItemName { get; set; }
        public IList<SelectListItem> lst_CustomerNameList { get; set; }
        public IList<SelectListItem> lst_ItemName { get; set; }
        public IList<SelectListItem> lst_State { get; set; }
        public List<string[]> Salesdetails { get; set; }

    }
}

DemoWebApplication/Controllers/SalesInvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoWebApplication.Models;
using PagedList;
using PagedList.Mvc;

namespace DemoWebApplication.Controllers
{
    public class SalesInvoiceController : Controller
    {
        DemoDbEntities dbcon = new DemoDbEntities();
        // GET: SalesInvoice
        public ActionResult Index()
        {
            return View();
        }
        private int BillNumber()
        {
            int? billno = 0;
            billno = dbcon.SalesInvoiceMasters.Max(x => (int?)x.Billno);
            billno = billno.HasValue ? billno + 1 : 1;
            return billno ?? 1;
        }
        //NonAction method can not used as like ActionMethod.   
        //This is used for processing and functionalities purpose.  
        [NonAction]
        public SelectList ToSelectList(List<SelectList> lstState)
        {
            List<SelectListItem> stateList = new List<SelectListItem>();

            stateList.Add(new SelectListItem { Text = "Maharashtra", Value = "1" });
            stateList.Add(new SelectListItem { Text = "MP", Value = "2" });
            stateList.Add(new SelectListItem { Text = "AP", Value = "3" });
            stateList.Add(new SelectListItem { Text = "UP", Value = "4" });
            stateList.Add(new SelectListItem { Text = "Goa", Value = "5" });
            return new SelectList(stateList, "Value", "Text");
        }
        public ActionResult CreateInvoice()
        {
            ViewBag.Message = null;
            SalesInvoice viewmodel = new SalesInvoice();
            List<SelectListItem> lst_Cust = new List<SelectListItem>();
            List<AccountMaster> custNamelist = dbcon.AccountMasters.ToList();
            custNamelist.ForEach(x =>
            {
                lst_Cust.Add(new SelectListItem { Text = x.AccountName, Value = x.AccountCode.ToString() });
            });
            viewmodel.lst_CustomerNameList = lst_Cust;
            List<SelectListItem> lst_Item = new List<SelectListItem>();
            var itemnames = dbcon.ItemMasters.Join(dbcon.ItemDetails, a => a.ItemCode, b => b.ItemMasterId, (a, b) => new { ItemMaster = a, ItemDetail = b }).ToList();
            itemnames.ForEach(x =>
            {
                lst_Item.Add(new SelectListItem { Text = x.ItemMaster.ItemName, Value = x.ItemDetail.ItemdetailId.ToString() });
            });
            viewmodel.lst_ItemName = lst_Item;
            List<SelectList> lstState = new List<SelectList>();
            SelectList result = ToSelectList(lstState);
            viewmodel.lst_State = result.ToList();
            viewmodel.Billno = BillNumber();
            viewmodel.Invoicedate = System.DateTime.Now;
            viewmodel.Duedate = DateTime.Now;
            viewmodel.CustState = "Maharashtra";
            viewmodel.SalesMasterId = 0;
            List<string[]> salesDetailsArray = new List<string[]>();
            viewmodel.Salesdetails = salesDetailsArray;
            return View(viewmodel);
        }
        [HttpPost]
        public ActionResult CreateInvoice(int Accountnumber, String Accountname, String CAddress, long Phoneno, String Billno, DateTime Invoicedate, DateTime Duedate, int Manualno, String CustState, String Paymentmode, bool DontApplyGst, String BillDiscount, String PaidAmount, String BalanceAmount, String NetBillAmount, String GstAmount, String TotalbillAmount, int SalesMasterId, SalesInvoiceDetail[] order)
         {
            ViewBag.Message = null;
            if(SalesMasterId == 0)
            {
            if (Accountname != null && order != null)
            {
                SalesInvoiceMaster data = new SalesInvoiceMaster();
                data.Accountnumber = Accountnumber;
                data.Accountname = Accountname;
                data.CAddress = CAddress;
                if (Phoneno == 0)
                    data.Phoneno = null;
                else
                    data.Phoneno = Phoneno;
                data.Billno =Convert.ToInt32(Billno);
                data.Invoicedate = Invoicedate;
                data.Duedate = Duedate;
                if (Manualno == 0)
                    data.Manualno = null;
                else
                    data.Manualno = Convert.ToString(Manualno);
                if (CustState == "")
                    data.CustState = "Maharashtra";
                else
                    data.CustState = CustState;
                if (Paymentmode == "Cash")
                    data.PaymentmodeCash = Convert.ToString(1);
                else
                    data.PaymentmodeCash = Convert.ToString(0);
                data.DontApplyGst = DontApplyGst;
                data.BillDiscount =Convert.ToDecimal(BillDiscount);
                data.NetBillAmount =Convert.ToDecimal(NetBillAmount);
                data.GstAmount = Convert.ToDecimal(GstAmount);
                data.Totalbillamount = Convert.ToDecimal(TotalbillAmount);
                data.Paidamount = Convert.ToDecimal(PaidAmount);
                data.Balanceamount = Convert.ToDecimal(BalanceAmount); 
                dbcon.SalesInvoiceMasters.Add(data);
                dbcon.SaveChanges();

                foreach(var item in order)
                {
                    SalesInvoiceDetail id = new SalesInvoiceDetail();
                    id.Accountnumber = Accountnumber;
                    id.Billno = Convert.ToInt32(Billno);
                    var batch = dbcon.BatchMasters.Where(x => x.BatchName == item.Batchno).FirstOrDefault();
                    var godown = dbcon.GodownMasters.Where(x => x.GodownName == item.Godown).FirstOrDefault();
                    var itemdetail = dbcon.ItemDetails.Where(x => x.ItemdetailId == item.Itemdetailid).FirstOrDefault();
                    var itemmaster = dbcon.ItemMasters.Where(x => x.ItemCode == itemdetail.ItemMasterId).FirstOrDefault();
                    id.SrNo = item.SrNo;
                    id.Itemdetailid = item.Itemdetailid;
                    id.Batchno = Convert.ToString(batch.BatchId);
                    id.Godown = Convert.ToString(godown.GodownId);
                    id.Expirydate = item.Expirydate;
                    id.qty = item.qty;
                    id.salesprice = item.salesprice;
                    id.disc = item.disc;
                    id.discamt = item.discamt;
                    id.NetAmount = item.NetAmount;
                    id.totalamount = item.totalamount;
                    id.HSNCode = itemmaster.HSNCODE;
                    id.MRP = itemdetail.MRP;
                    id.PurchasePrice = itemdetail.PurchasePrice;
                    id.GST = item.GST;
                    id.IGST = item.GST;
                    if (DontApplyGst)
                    {
                        id.SrNo = 0;id.CGST = 0;
                        id.IGST = 0;
                    }
                    else
                    {
                        id.SGST = item.GST / 2;
                        id.CGST = item.GST / 2;
                    }
                    
                    id.SGSTAmt = item.SGSTAmt;
                    id.CGSTAmt = item.CGSTAmt;
                    id.IGSTAmt = item.IGSTAmt;
                    id.SGSTTaxableAmt =Convert.ToInt32( item.NetAmount - item.discamt);
                    id.CGSTTaxableAmt =Convert.ToInt32( item.NetAmount - item.discamt);
                    if (item.IGSTAmt == 0)
                    {
                        id.IGST = 0;
                        id.IGSTTaxableAmt = 0;
                    }
                    else
                    {
                        id.IGSTTaxableAmt = Convert.ToInt32(item.NetAmount - item.discamt);
                    }
                    dbcon.SalesInvoiceDetails.Add(id);
                    dbcon.SaveChanges();
                }
            }
            //ModelState.Clear();
            //ViewBag.Message = "Invoice Saved";
            return Json(new { success = true, message = "Invoice created successfully" });
                // return RedirectToAction("CreateInvoice");
            }
            else
            {
                int billno = Convert.ToInt32(Billno);
                var salesmaster = dbcon.SalesInvoiceMasters.SingleOrDefault(x => x.Billno == billno);
                var salesitemDetails = dbcon.SalesInvoiceDetails.Where(x => x.Billno == billno).FirstOrDefault();
                if (salesmaster != null && salesitemDetails != null)
                {
                    dbcon.SalesInvoiceMasters.Remove(salesmaster);
                    dbcon.SalesInvoiceDetails.Remove(salesitemDetails);
                    dbcon.SaveChanges();

                    SalesInvoiceMaster data = new SalesInvoiceMaster();
                    data.Accountnumber = Accountnumber;
                    data.Accountname = Accountname;
                    data.CAddress = CAddress;
                    if (Phoneno == 0)
                        data.Phoneno = null;
                    else
                        data.Phoneno = Phoneno;
                    data.Billno = Convert.ToInt32(Billno);
                    data.Invoicedate = Invoicedate;
                    data.Duedate = Duedate;
                    if (Manualno == 0)
                        data.Manualno = null;
                    else
                        data.Manualno = Convert.ToString(Manualno);
                    if (CustState == "")
                        data.CustState = "Maharashtra";
                    else
                        data.CustState = CustState;
                    if (Paymentmode == "Cash")
                        data.PaymentmodeCash = Convert.ToString(1);
                    else
                        data.PaymentmodeCash = Convert.ToString(0);
                    data.DontApplyGst = DontApplyGst;
                    data.BillDiscount = Convert.ToDecimal(BillDiscount);
                    data.NetBillAmount = Convert.ToDecimal(NetBillAmount);

DemoWebApplication/Views/SalesInvoice/ShowAllInvoice.cshtml
@*@model IEnumerable<DemoWebApplication.SalesInvoiceMaster>*@
@model IPagedList<DemoWebApplication.SalesInvoiceMaster>

@using PagedList;
@using PagedList.Mvc;
<h2>sales Data</h2>
@{
    if (ViewBag.Message != null)
    {
        <script>
            alert(@Html.Raw(Json.Encode(ViewBag.Message)));
        </script>
    }
    int srno = 1 + Model.PageSize * (Model.PageNumber - 1);
}
@Html.AntiForgeryToken()
<p>
    @Html.ActionLink("Create Invoice", "CreateInvoice")
</p>

<table class="table" style="border:0.5px">
    <thead>
        <tr>
            <th>@Html.DisplayName("SrNo") </th>
            <th>@Html.DisplayNameFor(x => x.First().Billno)</th>
            <th>@Html.DisplayName("Date")</th>
            <th>@Html.DisplayName("Name")</th>
            <th>@Html.DisplayName("Payment Mode")</th>
            <th>@Html.DisplayName("Net Amount")</th>
            <th>@Html.DisplayNameFor(x => x.First().BillDiscount)</th>
            <th>@Html.DisplayNameFor(x => x.First().GstAmount)</th>
            <th>@Html.DisplayNameFor(x => x.First().Totalbillamount)</th>
            <th>@Html.DisplayNameFor(x => x.First().Paidamount)</th>
            <th>@Html.DisplayNameFor(x => x.First().Balanceamount)</th>
            <th>@Html.DisplayName("  Action  ") </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var bill in Model)
        {
            <tr>
                <td>@srno</td>
                <td>@Html.DisplayFor(x => bill.Billno)</td>
                <td>@Html.DisplayFor(x => bill.Invoicedate, "{0:dd/MMM/yyyy}")</td>
                <td>@Html.DisplayFor(x => bill.Accountname)</td>
                <td>
                    @{ if (bill.PaymentmodeCash == "1")
                        {
                            @Html.DisplayName("Cash")
                        }
                        else
                        { @Html.DisplayName("Credit")}
                    }
                </td>
                <td>@Html.DisplayFor(x => bill.NetBillAmount)</td>
                <td>@Html.DisplayFor(x => bill.BillDiscount)</td>
                <td>@Html.DisplayFor(x => bill.GstAmount)</td>
                <td>@Html.DisplayFor(x => bill.Totalbillamount)</td>
                <td>@Html.DisplayFor(x => bill.Paidamount)</td>
                <td>@Html.DisplayFor(x => bill.Balanceamount)</td>
                <td>
                    <input type="button" id="btn_Edit" value="Edit" class="btn btn-default" onclick='return Edit(@bill.Billno)' />
                    <input type="button" value="Delete" id="btn_Delete" class="btn btn-default" onclick='return Validation(@bill.Billno)' />
                </td>
            </tr>
            srno += 1;
        }
    </tbody>

</table>
@Html.PagedListPager(Model, i => Url.Action("ShowAllInvoice", "SalesInvoice", new { i }))
@*@Html.PagedListPager(Model, i => Url.Action("Index", "ItemDetail", new { i, search = Request.QueryString["search"] }))*@

<script>
    function Validation(billno) {
        if (confirm("Do you want to delete invoice no " + billno) == true) {
            //return true;
            $.ajax({
                url: "/SalesInvoice/DeleteInvoice",
                type: "post",
                dataType: "json",
                data: { id: billno },
                success: function (result) {
                    debugger;
                    alert(result.message);
                    location.reload();
                },
                error: function (err) {
                    debugger;
                    alert("Error occur in delete ");
                }
            });
        }
        else {
            return false;
        }
    }

    function Edit(billno) {
        debugger;
        if (confirm("Do you want to Modify invoice no " + billno) == true) {
            var url = '/SalesInvoice/Edit?id=' + encodeURIComponent(billno);
            // Redirect to the specified URL
            window.location.href = url;

            //$.post("Edit", { id: billno })
            //.done(function (response) {
            //    // Handle the successful response from the server
            //    alert("POST request successful");
            //})
            //.fail(function (xhr, status, error) {
            //    // Handle any error that occurred during the request
            //    debugger;
            //    Console.log(error);
            //    alert("Error in post request");
            //});
        }
        else {

        }
    }
</script>