DemoWebApplication/Controllers/ItemDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using DemoWebApplication.Models;
using Newtonsoft.Json;
using System.Net;
using System.Data;
using System.Data.Entity;
using PagedList;
using PagedList.Mvc;

namespace DemoWebApplication.Controllers
{
    public class ItemDetailController : Controller
    {
        DemoDbEntities dbcon = new DemoDbEntities();
        // GET: ItemDetail
        public ActionResult Index(string search,int ? i)
        {
            
            List<ItemDetail> itemdetaillist = new List<ItemDetail>();
            var result = dbcon.ItemDetails.ToList();
            var itemtypesdata = dbcon.ItemMasters.Join(dbcon.ItemDetails, a => a.ItemCode, b => b.ItemMasterId, (a, b) => new { ItemMasters = a, ItemDetail = b }).Where(ab => ab.ItemMasters.ItemCode == ab.ItemDetail.ItemMasterId).Select(ab => ab.ItemMasters.ItemName).Distinct();    //
            var itemData = dbcon.ItemMasters.Join(dbcon.ItemDetails, a => a.ItemCode, b => b.ItemMasterId, (a, b) => new { ItemMaster = a, ItemDetail = b }).Where(x=>x.ItemMaster.ItemName.StartsWith(search)||search==null).ToList();

            var newItemData = dbcon.ItemMasters.Join(dbcon.ItemDetails, a => a.ItemCode, b => b.ItemMasterId,
        (a, b) => new { ItemMaster = a, ItemDetail = b }).Select(ab => new
        {
            ItemName = ab.ItemMaster.ItemName,
            ItemDetailsId = ab.ItemDetail.ItemdetailId ,
            ItemMasterId = ab.ItemDetail.ItemMasterId
        }).ToList();
            foreach (var item in itemData)    // change result to itemData for working with joins operation
            {
                ItemDetail id = new ItemDetail();
                var itemnamedata = dbcon.ItemMasters.Where(x => x.ItemCode == item.ItemDetail.ItemMasterId).FirstOrDefault();
                var itemtypedata = dbcon.ItemTypes.Where(x => x.TypeId == itemnamedata.ItemType).FirstOrDefault();
                //var itemtypesdata = dbcon.ItemMasters.Join(dbcon.ItemTypes, a => a.ItemCode, b => b.TypeId, (a, b) => new { ItemMasters = a, ItemTypes = b }).Where(ab => ab.ItemMasters.ItemCode == ab.ItemTypes.TypeId).Select(ab => ab.ItemTypes.TypeName).Distinct();
                var godowndata = dbcon.GodownMasters.Where(x => x.GodownId == item.ItemDetail.GodownId).FirstOrDefault();
                var UnitData = dbcon.UnitMasters.Where(x => x.UnitId == item.ItemDetail.UnitId).FirstOrDefault();
                id.ItemdetailId = item.ItemDetail.ItemdetailId;
                id.ItemMasterId = item.ItemDetail.ItemMasterId;
                id.ItemName = item.ItemMaster.ItemName;
                id.ItemType = itemtypedata.TypeName;
                //var type= itemtypesdata.Select(data => data.TypeName);
                //id.ItemType = type;
                id.Godown = godowndata.GodownName;
                id.Unit = UnitData.UnitName;
                id.BatchId = item.ItemDetail.BatchId;
                id.BatchName = item.ItemDetail.BatchName;
                id.HsnCode = itemnamedata.HSNCODE;
                id.DiscPer = item.ItemDetail.DiscPer;
                id.Expirydate = item.ItemDetail.Expirydate;  //.HasValue  ? Formatting(item.Expirydate,"dd/MMM/yyyy") : "");
                id.PurchasePrice = item.ItemDetail.PurchasePrice;
                id.MRP = item.ItemDetail.MRP;
                id.OpeningStock = item.ItemDetail.OpeningStock;
                id.ClosingStock = item.ItemDetail.ClosingStock;
                
                itemdetaillist.Add(id);
            }
            return View(itemdetaillist.ToPagedList(i ?? 1, 4));
        }
        //private ItemDetail GetItemsList(int currentPage)
        //{

        //}
        [HttpGet]
        public ActionResult Create()
        {
            DemoWebApplication.Models.ItemDetailM viewmodel = new DemoWebApplication.Models.ItemDetailM();
            List<SelectListItem> Itemdetailnames = new List<SelectListItem>();
            List<ItemMaster> itemname = dbcon.ItemMasters.ToList();
            itemname.ForEach(x =>
            {
                Itemdetailnames.Add(new SelectListItem { Text = x.ItemName, Value = x.ItemCode.ToString() });
            });
            viewmodel.itemDetailList = Itemdetailnames;
            List<SelectListItem> Itemtypenames = new List<SelectListItem>();
            List<ItemType> itemtype = dbcon.ItemTypes.ToList();
            itemtype.ForEach(x =>
            {
                Itemtypenames.Add(new SelectListItem { Text = x.TypeName, Value = x.TypeId.ToString() });
            });
            viewmodel.lstitemtypes = Itemtypenames;
            List<SelectListItem> Itemunitnames = new List<SelectListItem>();
            List<UnitMaster> unitlist = dbcon.UnitMasters.ToList();
            unitlist.ForEach(x =>
            {
                Itemunitnames.Add(new SelectListItem { Text = x.UnitName, Value = x.UnitId.ToString() });
            });
            viewmodel.lstunits = Itemunitnames;
            List<SelectListItem> Itemgodownnames = new List<SelectListItem>();
            List<GodownMaster> godownlist = dbcon.GodownMasters.ToList();
            godownlist.ForEach(x =>
            {
                Itemgodownnames.Add(new SelectListItem { Text = x.GodownName, Value = x.GodownId.ToString() });
            });
            viewmodel.lstgodowns = Itemgodownnames;
            List<SelectListItem> Itembatchnames = new List<SelectListItem>();
            List<BatchMaster> batchlist = dbcon.BatchMasters.ToList();
            batchlist.ForEach(x =>
            {
                Itembatchnames.Add(new SelectListItem { Text = x.BatchName, Value = x.BatchId.ToString() });
            });
            viewmodel.lstbatches = Itembatchnames;
            //viewmodel.mfrdate = DateTime.Now;
            //viewmodel.Expirydate = DateTime.Now;

            return View(viewmodel);
        }
        [HttpPost]
        public ActionResult Create(ItemDetail item)
        {
            if (item != null)
            {
                if (item.ItemMasterId < 1)
                {
                    ModelState.AddModelError("ItemName", "Please Enter Item Name");
                    return View();
                }
                else if (item.GodownId < 1)
                {
                    ModelState.AddModelError("Godown", "Please Enter Godown");
                    return View();
                }
                else if (item.OpeningStock < 1)
                {
                    ModelState.AddModelError("OpeningStock", "Please Enter Opening Stock");
                    return View();
                }
            }
            int batchid = 0;
            string batchname = "";
            if (item.BatchId != null)
            {
                batchid = item.BatchId.HasValue ? (int)item.BatchId : 0;
                batchname = item.BatchName;
            }
            else
            {
                BatchMaster bm = new BatchMaster();
                bm.BatchName = item.BatchName;
                bm.Discription = "";
                dbcon.BatchMasters.Add(bm);
                dbcon.SaveChanges();
                var chk_batchname = dbcon.BatchMasters.Where(x => x.BatchName == item.BatchName).FirstOrDefault();
                {
                    batchid = chk_batchname.BatchId;
                    batchname = chk_batchname.BatchName;
                }
            }

            ItemDetail newitem = new ItemDetail();
            //newitem.ItemMasterId = Convert.ToInt32(item.ItemName);
            newitem.ItemMasterId = item.ItemMasterId;
            newitem.GodownId = item.GodownId;
            newitem.BatchId = batchid;//Convert.ToInt32(item.BatchName);
            newitem.BatchName = batchname;
            newitem.UnitId = item.UnitId;
            newitem.mfrdate = item.mfrdate;
            newitem.Expirydate = item.Expirydate;
            newitem.PurchasePrice = item.PurchasePrice;
            newitem.MRP = item.MRP;
            newitem.OpeningStock = item.OpeningStock;
            newitem.ClosingStock = item.ClosingStock;
            newitem.DiscPer = item.DiscPer;
            dbcon.ItemDetails.Add(newitem);
            dbcon.SaveChanges();
            ViewBag.Message = "Item Save Scessfully";
            ModelState.Clear();
            DemoWebApplication.Models.ItemDetailM viewmodel = new DemoWebApplication.Models.ItemDetailM();
            List<SelectListItem> Itemdetailnames = new List<SelectListItem>();
            List<ItemMaster> itemname = dbcon.ItemMasters.ToList();
            itemname.ForEach(x =>
            {
                Itemdetailnames.Add(new SelectListItem { Text = x.ItemName, Value = x.ItemCode.ToString() });
            });
            viewmodel.itemDetailList = Itemdetailnames;
            List<SelectListItem> Itemtypenames = new List<SelectListItem>();
            List<ItemType> itemtype = dbcon.ItemTypes.ToList();
            itemtype.ForEach(x =>
            {
                Itemtypenames.Add(new SelectListItem { Text = x.TypeName, Value = x.TypeId.ToString() });
            });
            viewmodel.lstitemtypes = Itemtypenames;
            List<SelectListItem> Itemunitnames = new List<SelectListItem>();
            List<UnitMaster> unitlist = dbcon.UnitMasters.ToList();
            unitlist.ForEach(x =>
            {
                Itemunitnames.Add(new SelectListItem { Text = x.UnitName, Value = x.UnitId.ToString() });
            });
            viewmodel.lstunits = Itemunitnames;
            List<SelectListItem> Itemgodownnames = new List<SelectListItem>();
            List<GodownMaster> godownlist = dbcon.GodownMasters.ToList();
            godownlist.ForEach(x =>
            {
                Itemgodownnames.Add(new SelectListItem { Text = x.GodownName, Value = x.GodownId.ToString() });
            });
            viewmodel.lstgodowns = Itemgodownnames;
            List<SelectListItem> Itembatchnames = new List<SelectListItem>();

DemoWebApplication/Views/ItemDetail/Index.cshtml
@*@model IEnumerable<DemoWebApplication.ItemDetail>*@
@model IPagedList<DemoWebApplication.ItemDetail>

@using PagedList;
@using PagedList.Mvc;

<h2>Item Details</h2>
@{
    if (ViewBag.Message != null)
    {
        <script>
            alert(@Html.Raw(Json.Encode(ViewBag.Message)));
        </script>
    }
}
@Html.AntiForgeryToken()
<p>
    @Html.ActionLink("Create New Item", "Create")
</p>
@using (Html.BeginForm("Index", "ItemDetail", FormMethod.Get))
{
    <input type="text" name="search" id="txt_search" />
    <input type="submit" value="Search" name="submit" />
}
<br />
<table class="table">
    <tr>
        <th>@Html.DisplayName("Sr No") </th>
        <th>@Html.DisplayNameFor(x => x.First().ItemName)</th>
        <th>@Html.DisplayNameFor(x => x.First().ItemType)</th>
        <th>@Html.DisplayNameFor(x => x.First().Godown)</th>
        <th>@Html.DisplayNameFor(x => x.First().BatchName)</th>
        <th>@Html.DisplayNameFor(x => x.First().Unit)</th>
        <th>@Html.DisplayNameFor(x => x.First().DiscPer)</th>
        <th>@Html.DisplayNameFor(x => x.First().HsnCode)</th>
        <th>@Html.DisplayNameFor(x => x.First().Expirydate)</th>
        <th>@Html.DisplayNameFor(x => x.First().PurchasePrice)</th>
        <th>@Html.DisplayNameFor(x => x.First().MRP)</th>
        <th>@Html.DisplayNameFor(x => x.First().OpeningStock)</th>
        <th>@Html.DisplayNameFor(x => x.First().ClosingStock)</th>
        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <h2>No Data To Show !</h2>
    }
    else
    {
        int srno= 1 + Model.PageSize * (Model.PageNumber - 1);
     

        foreach (var item in Model)
        {
            <tr>
                <th>@srno </th>
                <th>@Html.DisplayFor(x => item.ItemName)</th>
                <th>@Html.DisplayFor(x => item.ItemType)</th>
                <th>@Html.DisplayFor(x => item.Godown)</th>
                <th>@Html.DisplayFor(x => item.BatchName)</th>
                <th>@Html.DisplayFor(x => item.Unit)</th>
                <th>@Html.DisplayFor(x => item.DiscPer)</th>
                <th>@Html.DisplayFor(x => item.HsnCode)</th>
                <th>@Html.DisplayFor(x => item.Expirydate)</th>
                <th>@Html.DisplayFor(x => item.PurchasePrice)</th>
                <th>@Html.DisplayFor(x => item.MRP)</th>
                <th>@Html.DisplayFor(x => item.OpeningStock)</th>
                <th>@Html.DisplayFor(x => item.ClosingStock)</th>
                <th>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ItemdetailId })|
                    @Html.ActionLink("Delete", "Delete", new { id = item.ItemdetailId }, new { onclick = "return Validation();" })
                </th>
            </tr>
            srno += 1;
        }
    }
       
</table>
@Html.PagedListPager(Model, i => Url.Action("Index", "ItemDetail", new { i, search = Request.QueryString["search"] }))
<script type="text/javascript">
    function Validation() {
        if (confirm("Do you want to delete this record !") == true) {
            return true;
        } else {
            return false;
        }
    }
</script>