DemoWebApplication/Controllers/ItemMasterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemoWebApplication.Services;
using DemoWebApplication.Enums;
using System.Data.Entity;
using DemoWebApplication.Models;
namespace DemoWebApplication.Controllers
{
    public class ItemMasterController : Controller
    {
        DemoDbEntities dbcon = new DemoDbEntities();

        // GET: ItemMaster
        public ActionResult Index()
        {
            List<ItemMaster> items = new List<ItemMaster>();
            var result = dbcon.ItemMasters.ToList();
            foreach(var item in result )
            {
                ItemMaster im = new ItemMaster();
                var itemTypedata = dbcon.ItemTypes.Where(x => x.TypeId == item.ItemType).FirstOrDefault();
                im.TypeName =itemTypedata.TypeName ;
                im.ItemCode = item.ItemCode;
                im.ItemName = item.ItemName;
                im.ItemType = item.ItemType;
                im.HSNCODE = item.HSNCODE;
                im.GstPer = item.GstPer;
                items.Add(im);
            }
            return View(items);
        }
        [HttpGet]
        public ActionResult AddItem()
        {
            ItemMaster viewmodel = new ItemMaster();
            List<SelectListItem> itemtypename = new List<SelectListItem>();
            List<ItemType> typelist = dbcon.ItemTypes.ToList();
            foreach(var type in typelist)
            {
                itemtypename.Add(new SelectListItem { Text = type.TypeName, Value = type.TypeId.ToString() });
            }
            viewmodel.itemtypes = itemtypename;
            return View(viewmodel );
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddItem([Bind] ItemMaster i)
        {
            ItemMaster viewmodel = new ItemMaster();
            List<SelectListItem> itemtypename = new List<SelectListItem>();
            List<ItemType> typelist = dbcon.ItemTypes.ToList();
            foreach (var type in typelist)
            {
                itemtypename.Add(new SelectListItem { Text = type.TypeName, Value = type.TypeId.ToString() });
            }
            viewmodel.itemtypes = itemtypename;

            ViewBag.Message = string.Format("");
            if (ModelState.IsValid)
            {
                var im = dbcon.ItemMasters.Where(x => x.ItemName == i.ItemName && x.ItemType == i.ItemType).FirstOrDefault();
                if (im == null)
                {
                    dbcon.ItemMasters.Add(i);
                    dbcon.SaveChanges();
                   // ViewBag.Message = String.Format("Item Name " + i.ItemName + " save succesfully");
                    ViewBag.Alert = CommonServices.ShowAlert(Alerts.Alert.Success, "Item Name " + i.ItemName + " save succesfully");  //String.Format("Item Name " + i.ItemName + " save succesfully");
                    ModelState.Clear();
                    return View(viewmodel);
                }
                else
                {
                    ViewBag.Alert = CommonServices.ShowAlert(Alerts.Alert.Warning, "Item Name " + i.ItemName + " With Item type " + i.ItemType + " already exist");
                   // ViewBag.Message = String.Format("Item Name "+ i.ItemName +" With Item type "+ i.ItemType + "already exist");
                    return View(i);
                }
               
            }
            else
            {
                ViewBag.Alert = CommonServices.ShowAlert(Alerts.Alert.Danger, "Please Enter Valid Details");
                //ViewBag.Message = String.Format("Please Enter Valid Details");
                return View(i);
            }
        }

        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemMaster i = dbcon.ItemMasters.Find(id);
            if (i == null)
            {
                return HttpNotFound();
            }
            List<SelectListItem> typelist = new List<SelectListItem>();
            List<ItemType> itemtypenames = dbcon.ItemTypes.ToList();
            foreach (var type in itemtypenames)
            {
                typelist.Add(new SelectListItem { Text = type.TypeName, Value = type.TypeId.ToString() });
            }
            i.itemtypes = typelist;
            TempData["ItemCode"] = id;
            TempData.Keep();
            return View(i);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ItemMaster i)
        {
            NumberFormatInfo formatProvider = new NumberFormatInfo();
            formatProvider.NumberDecimalSeparator = ", ";
            formatProvider.NumberGroupSeparator = ".";
            formatProvider.NumberGroupSizes = new int[] { 2 };
            Double itemcode = Convert.ToDouble(TempData["ItemCode"], formatProvider);
            var im = dbcon.ItemMasters.Where(x => x.ItemCode == itemcode).FirstOrDefault();
            if (ModelState.IsValid)
            {
                if (im != null)
                {
                    im.ItemName = i.ItemName;
                    im.ItemType = i.ItemType;
                    im.HSNCODE = i.HSNCODE;
                    im.GstPer = i.GstPer;
                    dbcon.Entry(im).State = EntityState.Modified;
                    dbcon.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                    return RedirectToAction("Edit");
            }
            else
                return RedirectToAction("Edit");
        }

        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemMaster im = dbcon.ItemMasters.Find(id);
            if (im == null)
            {
                return HttpNotFound();
            }
            return View(im);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(long id)
        {
            ItemMaster im = dbcon.ItemMasters.Find(id);
            dbcon.ItemMasters.Remove(im);
            dbcon.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DemoWebApplication/Controllers/ItemTypeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DemoWebApplication.Controllers
{
    public class ItemTypeController : Controller
    {
        DemoDbEntities dbcon = new DemoDbEntities();
        // GET: ItemType
        public ActionResult Index()
        {
            return View(dbcon.ItemTypes.ToList());
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost ]
        public ActionResult Create([Bind] ItemType type)  
        {
            ViewBag.Message = null;
            if (string.IsNullOrEmpty(type.TypeName))
            {
                ModelState.AddModelError("ItemTypeName", "Plz Enter Item Type Name");
                return View();
            }
            else
            { 
            dbcon.ItemTypes.Add(type);
            dbcon.SaveChanges();
            ViewBag.Message="Item Type "+type.TypeName +" saved";
            ModelState.Clear();
            return View();
            }
        }
        [HttpGet]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var itemtype = dbcon.ItemTypes.Find(id);
            if (itemtype == null)
                return HttpNotFound();
            TempData["TypeId"] = id;
            TempData.Keep();
            return View(itemtype);
        }
        [HttpPost]
        public ActionResult Edit([Bind]ItemType type)
        {
            if (String.IsNullOrEmpty(type.TypeName))
            {
                ModelState.AddModelError("Typename", "Please Enter Type name");
                return View(type);
            }
            NumberFormatInfo formatprovide = new NumberFormatInfo();
            formatprovide.NumberDecimalSeparator = ",";
            formatprovide.NumberGroupSeparator = ".";
            formatprovide.NumberGroupSizes = new int[] { 2 };
            Double itemtypeid = Convert.ToDouble(TempData["TypeId"],formatprovide);
            var it = dbcon.ItemTypes.Where(x => x.TypeId == itemtypeid).FirstOrDefault();
            if (it != null)
            {
                it.TypeName = type.TypeName;
                it.Details = type.Details;
                dbcon.Entry(it).State = EntityState.Modified;
                dbcon.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return View(type);
        }

        [HttpPost]
        public ActionResult Delete([Bind] ItemType deletetype)
        {
            dbcon.ItemTypes.Remove(deletetype);
            dbcon.SaveChanges();
            return View("Index");
        }
        
    }
}

DemoWebApplication/Views/ItemMaster/AddItem.cshtml
@model DemoWebApplication.ItemMaster

<script src="~/Scripts/MyJs.js"></script>
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class=" form-horizontal" id="myDIV">
        <h4>Create New Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ItemCode)
        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, "Item Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class=" col-md-10">
                @Html.EditorFor(model => model.ItemName, new { htmlattributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class=" form-group ">
            @Html.LabelFor(model => model.ItemType, "Item Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-4 col-xs-push-0">
                @Html.DropDownListFor(model => model.ItemType, Model.itemtypes,"--Select--",  new { @class = "form-control"  })
                @*<input type="button" value="N" id="btn_newType"  />*@
                @Html.ValidationMessageFor(model => model.ItemType, "", new { @class = "text-danger col-md-10" })
            </div>
        </div>
        <div class="form-group ">
            @Html.LabelFor(model => model.HSNCODE, "HSN Code", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HSNCODE, new { htmlAttributes = new { @class = "form-control", id = "txt_Hsncode" } })
                @Html.ValidationMessageFor(x => x.HSNCODE, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group ">
            @Html.LabelFor(model => model.GstPer, "GST %", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GstPer, new { htmlattributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GstPer, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" id="btn_Save" runat="server" onclick="btn_Save_Click" OnClientClick="return Validations();" />
                <input type="button" value="Cancle" class="btn btn-default" id="btn_Cancle" onclick="ClearAllItem()" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">@Html.Raw(ViewBag.Alert)</div>
            </div>
        </div>
        <p>
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
}
<script>
    $(document).ready(function () {
        $('#btn_Save').click(function () {
            var hsncode = $('#txt_Hsncode').text();
            if (hsncode == '') {
                alert("Please Enter HSN Code For Item");
                ViewBag.Alert = CommonServices.ShowAlert(Alerts.Alert.Warning, "Please Enter HSN Code For Item");
                return false;
            }
        });
        $('#btn_newType').click(function () {
            RenderAction("Index", "ItemType");
        });
    });
</script>

@*@if (ViewBag.Message != null)   // replace alert with Bootstrap alert Msg
    {
        <script type="text/javascript">
                window.onload = function () {
                    alert("@ViewBag.Message");
                };
        </script>
    }*@

DemoWebApplication/Views/ItemMaster/Delete.cshtml
@model DemoWebApplication.ItemMaster
    <h3>Delete Item</h3>
<h4>Are u sure to delete this record</h4>
<hr />
<h4> Item Details</h4>
<div class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(x=>x.ItemName)
    </dt>
    <dd>
        @Html.DisplayFor(x=>x.ItemName)
    </dd>
    <dt>
        @Html.DisplayNameFor(x=>x.ItemType)
    </dt>
    <dd>@Html.DisplayFor(x=>x.ItemType)</dd>
    <dt>@Html.DisplayNameFor(x=>x.HSNCODE)</dt>
    <dd>@Html.DisplayFor(x=>x.HSNCODE)</dd>
    <dt>@Html.DisplayNameFor(x=>x.GstPer)</dt>
    <dd>@Html.DisplayFor(x=>x.GstPer)</dd>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken();
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            @Html.ActionLink("Back to List","Index")
        </div>
    }
</div>

DemoWebApplication/Views/ItemMaster/Edit.cshtml
@model DemoWebApplication.ItemMaster
<h4>Edit Item</h4>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(x => x.ItemCode)
        <div class="form-group">
            @Html.LabelFor(x => x.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(x => x.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(x => x.ItemName, "", new { @Class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.ItemType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.ItemType,Model.itemtypes,"" , new { @class = "form-control"  })
                @Html.ValidationMessageFor(x => x.ItemType, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.HSNCODE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(x => x.HSNCODE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(x => x.HSNCODE, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x=>x.GstPer,"Gst %",htmlAttributes: new {@class="control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(x => x.GstPer, new { htmlAttributes = new { @class ="form-control"} })
                @Html.ValidationMessageFor(x => x.GstPer, "", new { @class="text-danger"})
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Modify" class="btn btn-default "/>
            </div>
        </div>
    </div>
}

DemoWebApplication/Views/ItemMaster/Index.cshtml
@model IEnumerable<DemoWebApplication.ItemMaster>
<h4>All items</h4>
<p>
    @Html.ActionLink("Create New Item","AddItem")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(x=>x.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(x=>x.ItemType)
        </th>
        <th>
            @Html.DisplayNameFor(x=>x.HSNCODE)
        </th>
        <th>
            @Html.DisplayNameFor(x=>x.GstPer)
        </th>
    </tr>
    @foreach(var item in Model)
    {
        <tr>
            <th>
               @Html.DisplayFor(x=>item.ItemName)
            </th>
            <th>
               @Html.DisplayFor(x=>item.TypeName)
            </th>
            <th>
               @Html.DisplayFor(x=>item.HSNCODE)
            </th>
            <th>
               @Html.DisplayFor(x=>item.GstPer)
            </th>
            <th>
                @Html.ActionLink("Edit", "Edit", new { id=item.ItemCode}) | 
                @Html.ActionLink("Delete", "Delete", new { id=item.ItemCode})
            </th>
        </tr>

    }
</table>